### ISSUE TITLE
Communicate with Budgets API

### ISSUE THREAD

**Issue by gabrielssilva** [GPP-MDS-2015-2/Aonde#10]
Get Public Agencies budget from the following API
http://orcamento.dados.gov.br/sparql

**Comment by marcelohpf** [comment]
Tasks: 
* [ ] Pesquisar como estão os dados da api
* [ ] Pesquisar como fazer o parser dos dados obtidos
* [ ] Utilizar alguns métodos
* [ ] Escolher qual a melhor forma para obter os dados
* [ ] Métodos de teste para receber dados da api
* [ ] Criar método para receber dados da api
* [ ] Testes para parser dos dados da api
* [ ] Métodos para fazer o parse dos dados da api
