### ISSUE TITLE
View Program

### ISSUE THREAD

**Issue by gabrielssilva** [GPP-MDS-2015-2/Aonde#17]
View which companies and public agencies are related to a specific program

**Comment by marcelohpf** [comment]
* [ ] Search best form to visualize the data
* [ ] Add web page and create routes
* [ ] Make test to routes and method 'show'
* [ ] Create test to manage datas of public agency and expenses
* [ ] Create method to manage datas of public agency and expenses
* [ ] Create test to calcule informations of public agencies
* [ ] Create method to calcule informations of public agencies
* [ ] Create the CSS to visualize the data
