### ISSUE TITLE
Compare Budgets with Expenses

### ISSUE THREAD

**Issue by gabrielssilva** [GPP-MDS-2015-2/Aonde#18]
Compare the budgets of a specific Public Agency with its total Expenses

**Comment by eduardonunes2525** [comment]
* [ ] test

**Comment by eduardonunes2525** [comment]
* [ ] Finding and Choosing the charts

**Comment by eduardonunes2525** [comment]
* [ ] Implement graphic

**Comment by eduardonunes2525** [comment]
* [ ] Create the subtraction method to budget
* [ ] Take the tests
* [ ] Do filter the years with the combobox
* [ ] Put the chart on both
