### ISSUE TITLE
Preprocess data

### ISSUE THREAD

**Issue by gabrielssilva** [GPP-MDS-2015-2/Aonde#37]
Change the data model to store total expenses in Public Agencies tables, and create a preprocessor script to accomplish this task

## Assignees
* @EduardoMoreira
* @gabrielssilva 

## Tasks
* [X] Create table to store preprocess data of public agencies expenses by year
* [X] Populate table

**Comment by EduardoMoreira** [comment]
Issue is resolved on the repository 'AondeParser' of the organization 'GPP-MDS-2015-2'.
